name: zaika_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  geolocator: ^13.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  google_fonts: ^6.3.2
  qr_flutter: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/zaika_logo.png
    - assets/images/zaika_text.png
    - assets/images/zaika_text_purple.png
    - assets/images/zaika_restaurant.jpeg
    - assets/images/book.jpeg
    - assets/images/menu.jpeg
    - assets/images/order.jpeg
    - assets/images/location.png
    - assets/images/location_icon.png
    - assets/images/mark.png
    - assets/images/success.jpeg

 